### ISSUE TITLE
收集贴: 使用本插件的服务器

### ISSUE THREAD

**Issue by way-zer** [way-zer/MyMindustryPlugin#1]
> 按留言顺序排序
- vps.wayzer.cf WayZer的服务器
- s.1812z.top 纯PVP服务器 @1812z
- mindustry.m6xy.cn "王者学院"服@Moyanxu
- m.tiexiu.xyz:30044 @Server-svg
- m.tiexiu.xyz:30085 @king-wang17
> 加入列表请在下方留言

**Comment by 1812z** [comment]
一个pvp服务器
s.1812z.top

**Comment by Moyanxu** [comment]
嘿嘿 mindustry.m6xy.cn王者学院服哦 MYX一直在用哦 那个提示可以改改吗 感谢！

**Comment by Server-svg** [comment]
m.tiexiu.xyz:30044
这个服务器正在测试插件，谢谢呢

**Comment by king-wang17** [comment]
m.tiexiu.xyz:30085
欢迎大家
