### ISSUE TITLE
[Feature Request] /vote mute or /vote ratelimit

### ISSUE THREAD

**Issue by commandblock2** [way-zer/MyMindustryPlugin#2]
![Screenshot_20221128_014056](https://user-images.githubusercontent.com/21105626/204151103-5f202aa3-ca01-4575-8231-68ec3a33cf1f.png)
![Screenshot_20221128_014148](https://user-images.githubusercontent.com/21105626/204151128-4d34f3d6-a95b-4c6c-9bb1-2242635c0bb1.png)
投票加一项功能
被投票的人禁言n分钟或者每n sec才能发一句话

**Comment by way-zer** [comment]
1. 该仓库已经归档了，主仓库是 https://github.com/way-zer/ScriptAgent4MindustryExt/
2. 没有增加投票禁言的原因是：禁言后和踢出没啥区别，没有辩解的机会
